#!/bin/bash
WATER="$WATER" STIR="$STIR" eval "echo Result in base bestchol: \$(tr -d '[[:space:]]' <<< \$(echo \$((36#$(echo \$WATER|tr a-z 0123456789)|36#$(echo \$STIR|tr a-z 0123456789)))|awk '{printf("%c", $1+55)}'))"
